title = "Alpaca BM2 Batter Safetymonitor Driver"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
threshold = 12
log_csv = true

[voltage_logger]
prefix = "volts"
interval = 30

[logging]
log_level = 'INFO'
log_to_stdout = true
max_size_mb = 50
num_keep_logs = 10
