title = "Alpaca BM2 Batter Safetymonitor Driver"

[network]
ip_address = ''             # Any address
port = 5555

[server]
location = 'Anywhere on Earth'  # Anything you want here
verbose_driver_exceptions = true

[device]
addr = 12345
threshold = 12

[logging]
log_level = 'INFO'
log_to_stdout = true
max_size_mb = 50
num_keep_logs = 10
